name: flutter_tabler
description: Just the Tabler.
version: 0.3.4
homepage: https://github.com/skyfet/tabler

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
